#include "pit.h"
#include "../i8259.h"
#include "../lib.h"
#include "../scheduler.h"
#include "../signal.h"

int32_t alarm_signal_counter = 0;

/* PIT_init - Initialization of Programmable Interval Timer (PIT)
 * 
 * Initializes the PIT to a frequency of 100Hz.
 *  
 * Inputs: none
 * Outputs: none
 * Side Effects: Modifies PIT Mode Register and Channel 0 Data Register
 */
void pit_init(void) {
    outb(MODE_CONTAIN, MODE_REG);
    outb((uint8_t)PIT_FREQ, CHAN_0_DATA_PORT);
    outb((uint8_t)(PIT_FREQ >> 8), CHAN_0_DATA_PORT);
    enable_irq(PIT_IRQ);
}

/* __intr_PIT_handler - Programmable Interval Timer (PIT) Interrupt Handler
 * 
 * Handles interrupts generated by the PIT.
 * 
 * Inputs: None (Triggered by PIT interrupt)
 * Outputs: None (Handles interrupt side effects)
 * Side Effects: Call the scheduler
 */
void __intr_PIT_handler(void) {
    alarm_signal_counter++;
    if(alarm_signal_counter >= 1000){
        alarm_signal_counter = 0;
        send_signal_by_pid(SIGNUM_ALARM, 3);
    }
    send_eoi(PIT_IRQ);
    scheduler();
}
